[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.nestix]
command = "cargo"
options = ["run"]
includes = ["*.nix"]

[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]
